[tools]
elixir = "latest"
erlang = "latest"
fzf = "latest"
go = "latest"
lazydocker = "latest"
ollama = "latest"
python = "latest"
rg = "latest"
sqlite = "latest"
typst = "latest"
uv = "latest"
zoxide = "latest"

[env]
